# name: CIi
# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:

# jobs:
#   build-frontend:
#     name: Build Frontend
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         node-version:
#           [20,22]

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Setup Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: ${{ matrix.node-version}}
#           cache: "npm"
#           cache-dependency-path: frontend/package-lock.json

#       - name: Install npm dependencies
#         run: npm ci
#         working-directory: frontend

#       - name: Run Linter
#         run: npm run lint
#         working-directory: frontend

#       - name: Run Tests
#         run: npm test
#         working-directory: frontend

#   build-backend:
#     name: Build Backend
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         go-version:
#           [1.24,1.25,1.26]
          
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Setup Go
#         uses: actions/setup-go@v5
#         with:
#           go-version: ${{ matrix.go-version }}
#           cache: true

#       - name: Install dependencies
#         run: go mod download
#         working-directory: backend

#       - name: Run Tests
#         run: go test ./...
#         working-directory: backend

#   deploy:
#     name: Deploy
#     needs: [build-frontend, build-backend]
#     uses: ./.github/workflows/docker.yml
#     secrets: inherit

