kind: Deployment
apiVersion: apps/v1
metadata:
  name: devboard-backend-deployment
  namespace: devboard
  labels:
    app: devboard-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devboard-backend
  template:
    metadata:
      labels:
        app: devboard-backend
    spec:
      containers:
        - name: devboard-backend
          image: elsa888/devboard-backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: PORT
              value: "8000"
            - name: POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: devboard-secret
                  key: POSTGRES_URL