kind: Service
apiVersion: v1
metadata:
  name: devboard-backend-service
  namespace: devboard
  labels:  
    app: devboard-backend
spec:
  type: NodePort
  selector:
    app: devboard-backend
  ports:
    - protocol: TCP
      port: 8080        # service (cluster-internal)
      targetPort: 8000  # actual container port
      nodePort: 30081   # external access
