apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-statefulset
  namespace: devboard
  labels:
    app: devboard-postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: devboard-postgres
  template:
    metadata:
      labels:
        app: devboard-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16-alpine
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: devboard-configmap
                key: POSTGRES_USER

          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: devboard-configmap
                key: POSTGRES_DB

          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: devboard-secret   # matches secrets.yml name
                key: POSTGRES_PASSWORD
        volumeMounts:
          - name: postgres-data
            mountPath: /var/lib/postgresql/data
          - name: postgres-init
            mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: postgres-init
          configMap:
            name: postgres-init
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
