apiVersion: v1
kind: Secret
metadata:
  name: devboard-secret
  namespace: devboard
type: Opaque
data:
  POSTGRES_PASSWORD: ZGV2Ym9hcmQ=
  POSTGRES_URL: cG9zdGdyZXM6Ly9kZXZib2FyZDpkZXZib2FyZEBwb3N0Z3Jlcy5kZXZib2FyZC5zdmMuY2x1c3Rlci5sb2NhbDo1NDMyL2RldmJvYXJkP3NzbG1vZGU9ZGlzYWJsZQ==
  POSTGRES_DB:  ZGV2Ym9hcmQ= # this decodes to devboard