name: Code Scan

on:
  workflow_call:

jobs:
  code-scanning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: javascript-typescript,go

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v4