name: Dependency Scan

on:
  workflow_call:

jobs:
  dependency-scan:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        folder:
          - frontend
          - backend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # -------------------------
      # FRONTEND
      # -------------------------

      - name: Setup Node
        if: matrix.folder == 'frontend'
        uses: actions/setup-node@v6
        with:
          node-version: '20'
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install Node Dependencies
        if: matrix.folder == 'frontend'
        working-directory: frontend
        run: npm ci

      - name: Create Reports Directory
        if: matrix.folder == 'frontend'
        run: mkdir -p reports

      - name: Run NPM Audit
        if: matrix.folder == 'frontend'
        working-directory: frontend
        run: |
          npm audit --json > ../reports/npm-audit-report.json || true

      - name: Enforce NPM Audit
        if: matrix.folder == 'frontend'
        working-directory: frontend
        run: |
          echo "Checking for Moderate, High and Critical vulnerabilities..."
          npm audit --audit-level=moderate

      # -------------------------
      # BACKEND
      # -------------------------

      - name: Setup Go
        if: matrix.folder == 'backend'
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'
          cache: true

      - name: Install Go Dependencies
        if: matrix.folder == 'backend'
        working-directory: backend
        run: go mod download

      - name: Install Govulncheck
        if: matrix.folder == 'backend'
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Run Govulncheck
        if: matrix.folder == 'backend'
        working-directory: backend
        run: |
          mkdir -p ../reports
          govulncheck -json ./... > ../reports/govulncheck-report.json || true

      - name: Enforce Go Vulnerabilities
        if: matrix.folder == 'backend'
        working-directory: backend
        run: |
          echo "Checking Go vulnerabilities..."
          govulncheck ./...

      # -------------------------
      # UPLOAD
      # -------------------------

      - name: Upload Dependency Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dependency-scan-report-${{ matrix.folder }}
          path: reports/
          retention-days: 5 