name: All Scanning

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  code-quality:
    uses: ./.github/workflows/code_quality.yml

  code-scan:
    uses: ./.github/workflows/code_scan.yml

  dependency-scan:
    uses: ./.github/workflows/dependency_scan.yml

  hadolint:
    uses: ./.github/workflows/hadolint.yml