name: "Job 5: IaC Security Scan"

on:
  workflow_call:

permissions:
  contents: read
  security-events: write

jobs:
  iac-security:
    name: "IaC Security Scan (Trivy Config)"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Trivy Config / IaC Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          scan-ref: '.'
          format: 'table'
          severity: 'CRITICAL,HIGH'
