name: "Job 9: Container Scan"

on:
  workflow_call:

permissions:
  contents: read
  security-events: write

jobs:
  container-scan:
    name: "Container Scan (Trivy)"
    runs-on: ubuntu-latest
    steps:
      - name: Download Image Artifacts
        uses: actions/download-artifact@v4
        with:
          name: docker-images
          path: image-artifacts

      - name: Load Docker Images
        run: |
          docker load -i image-artifacts/devboard-backend.tar
          docker load -i image-artifacts/devboard-frontend.tar
      - name: Scan Backend Container Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'devboard-backend:${{ github.sha }}'
          format: 'table'
          severity: 'CRITICAL,HIGH'

      - name: Scan Frontend Container Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'devboard-frontend:${{ github.sha }}'
          format: 'table'
          severity: 'CRITICAL,HIGH'
