name: "Job 3: SAST (SonarQube)"

on:
  workflow_call:

permissions:
  contents: read
  security-events: write

jobs:
  sast-sonarqube:
    name: "SAST (SonarQube)"
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        continue-on-error: true
